### ISSUE TITLE
incomplete documentation for /api/services

### ISSUE THREAD

**Issue by mkoura** [ManageIQ/manageiq_docs#197]
Actions "create", "set_ownership", "start", "stop" and "suspend" are not documented.

**Comment by chessbyte** [comment]
@abellotti is this old issue still valid?

**Comment by abellotti** [comment]
/api/services actions include:
- [X] create  (_on collection endpoint_)
- [X] add_provider_vms
- [X] add_resource
- [X] delete
- [X] edit
- [ ] queue_chargeback_report
- [X] request_retire
- [X] reconfigure
- [X] remove_all_resources
- [X] remve_resource
- [X] set_ownership - mentioned in: https://www.manageiq.org/docs/reference/latest/api/reference/ownership
- [X] start
- [X] stop
- [X] suspend

Unless otherwise noted, the documentation currently exists in: https://www.manageiq.org/docs/reference/latest/api/reference/services#services

While the actions mentioned in this Issue's description are all documented, the one action for /api/services that is not documented is **queue_chargeback_report**.
